name: Deployment workflow
on:
  push:
    branches: [ "main" ]

jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build


      - name: Telegram Notifications
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ${{ github.actor }} created commit:
             Commit message: ${{ github.event.commits[0].message }}

             Repository: ${{ github.repository }}

             See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

             🎉 **`${{ github.actor }}`** aka ${{ steps.tagged.outputs.reviewer }} send message from 🍻  
              Repository: https://github.com/${{ github.repository }}


