name: Deployment workflow
on:
  push:
    branches: [ "dev" ]


jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build

      - name: Create Pull Request on Success
        if: success()
        run: |
          git config user.name "ismoillmirabbosoff"
          git config user.email "ismoillmirabbosoff@users.noreply.github.com"

          # Check if 'main' branch exists, otherwise use another branch
          DEFAULT_BRANCH="main"
          if git show-ref --quiet refs/heads/$DEFAULT_BRANCH; then
            git checkout $DEFAULT_BRANCH
          else
            # Fallback to another branch if 'main' doesn't exist
            DEFAULT_BRANCH="dev"
            git checkout $DEFAULT_BRANCH
          fi

          git branch -D dev  # Delete the existing 'dev' branch
          git checkout -b dev  # Create a new 'dev' branch
          git commit -am "Auto-commit on successful build"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: 'main'
          head: 'dev'
          title: 'Auto-generated pull request'
          body: 'This pull request was automatically generated.'

      - name: Telegram Notifications on Success
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ${{ github.actor }} successfully created commit ❌❌❌:
             Commit message: ${{ github.event.commits[0].message }}
             Repository: ${{ github.repository }}
             See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}


      - name: Telegram Notifications on Failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ${{ github.actor }} successfully created commit ❌❌❌:
             Commit message: ${{ github.event.commits[0].message }}
             Repository: ${{ github.repository }}
             See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
